# Generated by Django 5.1.4 on 2025-09-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiparser', '0002_product_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file_url_2',
            field=models.URLField(blank=True, null=True, verbose_name='File URL 2'),
        ),
    ]
