# Generated by Django 5.1.4 on 2025-09-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiparser', '0003_product_file_url_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='delete_from_server',
            field=models.BooleanField(default=False, verbose_name='Delete from Server'),
        ),
        migrations.AddField(
            model_name='document',
            name='telegram_file_id',
            field=models.CharField(blank=True, help_text='File ID after sending to Telegram channel', max_length=255, null=True, verbose_name='Telegram File ID'),
        ),
        migrations.AddField(
            model_name='document',
            name='telegram_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', help_text='Status of sending to Telegram channel', max_length=255, verbose_name='Telegram Status'),
        ),
    ]
