# Generated by Django 5.1.4 on 2025-09-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiparser', '0004_document_delete_from_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='telegram_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', help_text='Status of sending to Telegram channel', max_length=255, verbose_name='Telegram Status'),
        ),
    ]
