# Generated by Django 5.1.4 on 2025-09-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiparser', '0005_alter_document_telegram_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_indexed',
            field=models.BooleanField(default=False, verbose_name='Is Indexed in Elasticsearch'),
        ),
    ]
