# Generated by Django 5.1.4 on 2025-09-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiparser', '0006_document_is_indexed'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size_bytes',
            field=models.BigIntegerField(default=0, help_text='Fayl hajmi (baytlarda)'),
        ),
    ]
