# Generated by Django 5.1.4 on 2025-09-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiparser', '0007_document_file_size_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Parsed Content'),
        ),
    ]
