# Generated by Django 5.1.4 on 2025-09-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiparser', '0008_product_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.AddField(
            model_name='document',
            name='parsed_content',
            field=models.TextField(blank=True, null=True, verbose_name='Parsed Content'),
        ),
    ]
