# Generated by Django 5.1.4 on 2025-01-04 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('webhook_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(blank=True, max_length=100, null=True)),
                ('bot_token', models.CharField(blank=True, max_length=100, null=True)),
                ('bot_token_name', models.CharField(blank=True, max_length=100, null=True)),
                ('channel_type', models.CharField(blank=True, choices=[('hashtag', 'Hashtag'), ('movie_base', 'Movie base'), ('trailer', 'Trailer'), ('db_backup', 'DB Backup'), ('log', 'Log')], max_length=20, null=True)),
                ('channel_id', models.CharField(max_length=100, unique=True)),
                ('channel_username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_unique_id', models.CharField(max_length=64, unique=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('code', models.IntegerField(default=0)),
                ('file_metadata', models.JSONField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('trailer_unique_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('trailer_metadata', models.JSONField(blank=True, null=True)),
                ('has_trailer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UnnecessaryWordFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_bot.bot')),
            ],
            options={
                'unique_together': {('telegram_id', 'bot')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_bot.user')),
            ],
        ),
    ]
