# Generated by Django 5.1.4 on 2025-01-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0002_alter_bot_options_bot_created_at_bot_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_language',
            field=models.CharField(blank=True, choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English'), ('tr', 'Turkish')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stock_language',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English'), ('tr', 'Turkish')], default='uz', max_length=10),
        ),
    ]
