# Generated by Django 5.1.4 on 2025-01-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0003_user_selected_language_user_stock_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('channel_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Channel_for_subscription',
                'verbose_name_plural': 'Channels_for_subscription',
                'ordering': ['-created_at'],
            },
        ),
    ]
