# Generated by Django 5.1.4 on 2025-01-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0004_subscribechannel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribechannel',
            options={'ordering': ['-created_at'], 'verbose_name': 'SubscriptionChannel', 'verbose_name_plural': 'SubscriptionChannel'},
        ),
        migrations.AlterField(
            model_name='subscribechannel',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
