# Generated by Django 5.1.4 on 2025-01-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0005_alter_subscribechannel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribechannel',
            name='channel_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscribechannel',
            name='channel_username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
