# Generated by Django 5.1.4 on 2025-01-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0006_alter_subscribechannel_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribechannel',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscribechannel',
            name='channel_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
