# Generated by Django 5.1.4 on 2025-01-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0011_rename_bot_token_name_channels_bot_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='bot_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
