# Generated by Django 5.1.4 on 2025-01-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0013_alter_channels_bot_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channels',
            options={},
        ),
        migrations.AlterField(
            model_name='channels',
            name='bot_token',
            field=models.CharField(max_length=100),
        ),
    ]
