# Generated by Django 5.1.4 on 2025-08-17 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0014_alter_channels_options_alter_channels_bot_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channels',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='UnnecessaryWordFilter',
        ),
    ]
