# Generated by Django 5.1.4 on 2025-08-17 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0015_delete_channels_delete_movie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'verbose_name': 'Bot', 'verbose_name_plural': 'Bots'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-created_at'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='subscribechannel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Subscription Channel', 'verbose_name_plural': 'Subscription Channels'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='bot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(blank=True, help_text='Auto-filled from Telegram API on save', max_length=100),
        ),
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(help_text='The unique token provided by @BotFather', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='username',
            field=models.CharField(blank=True, help_text='Auto-filled from Telegram API on save', max_length=100),
        ),
        migrations.AlterField(
            model_name='bot',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='Auto-filled on save', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='common_bot.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='common_bot.bot'),
        ),
    ]
