# Generated by Django 5.1.4 on 2025-08-17 23:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0018_broadcast_broadcastrecipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcast',
            options={},
        ),
        migrations.AlterModelOptions(
            name='broadcastrecipient',
            options={},
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='scheduled_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
