# Generated by Django 5.1.4 on 2025-08-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0019_alter_broadcast_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='left',
            field=models.BooleanField(default=False),
        ),
    ]
