# Generated by Django 5.1.4 on 2025-09-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='search_mode',
            field=models.CharField(choices=[('normal', 'Normal'), ('deep', 'Deep')], default='normal', max_length=10),
        ),
    ]
