# Generated by Django 5.1.4 on 2025-01-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0007_subscribechannel_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribechannel',
            name='channel_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
