# Generated by Django 5.1.4 on 2025-01-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0008_subscribechannel_channel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
