# Generated by Django 5.1.4 on 2025-01-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0009_movie_movie_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deeplink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
