# Generated by Django 5.1.4 on 2025-01-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0010_user_deeplink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channels',
            old_name='bot_token_name',
            new_name='bot_name',
        ),
        migrations.AddField(
            model_name='channels',
            name='bot_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='channels',
            name='channel_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='channels',
            name='bot_token',
            field=models.CharField(max_length=100),
        ),
    ]
