# Generated by Django 5.1.4 on 2025-01-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0012_alter_channels_bot_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='bot_token',
            field=models.CharField(default='8077184673:AAGD766S49G9ZUWdNToK-MqJBGtrUTljJnM', max_length=100),
        ),
    ]
