# Generated by Django 5.1.4 on 2025-08-17 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0016_alter_bot_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribechannel',
            name='token',
        ),
        migrations.AddField(
            model_name='subscribechannel',
            name='bot',
            field=models.ForeignKey(blank=True, help_text='The bot that manages this channel.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_channels', to='common_bot.bot'),
        ),
    ]
