# Generated by Django 5.1.4 on 2025-09-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0020_user_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='subscribechannel',
            name='bot',
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='bot',
        ),
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
